services:
  - type: web
    name: shine2-medical-backend
    env: python
    region: oregon
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd codezilla_spider/backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: NODE_VERSION
        value: 18
    rootDir: codezilla_spider
